### ISSUE TITLE
how to factory reset zutilo?

### ISSUE THREAD

**Issue by snam24** [wshanks/Zutilo#205]
Hi, I've been experiencing an error in zutilo and would like to factory reset it (reinstalling didn't help.)

I assigned some awkward shortcut to "Item pane: Add note" by accident.
Not only does every zutilo-style shortcut trigger adding note, but also I cannot change the shortcut assigned, nor can I see which shortcut I assigned... (screenshot: https://www.dropbox.com/s/b5h4nrghc7drxbr/Screenshot_2021-09-06-10_34_28_7517de.png?dl=0 )

I tried deleting/disabling/reinstalling the plugin, but neither helped. Can you please educate me on how to factory reset the package? The plugin has been so useful that I can't live without it. Thanks!

I'm on Zotero 5.0.97-beta.43+c5d89f6d0 and Zutilo 3.10.0

**Comment by wshanks** [comment]
In the config editor (Zotero preferences -> "Advanced" tab -> "Config editor" button near bottom), click the button to accept the risk and then in the search box at the top type "zutilo.shortcut" and then click "Status" to sort by status so the modified items are at the top. Then you can right-click and select "Reset" to reset any shortcut settings that you want. That should be sufficient. For more of a factory reset, you could type only "zutilo" instead of "zutilo.shortcut" and also reset other settings there.

**Comment by qqobb** [comment]
@snam24: Could you fix your Zutilo issue through Zotero's [Config Editor](https://www.zotero.org/support/preferences/advanced#general)? If not, please reopen this issue.

See also #223 regarding the "Item pane: Add note" shortcut. I'd recommend Zotero's shortcut instead.
